site_name: OpenVK Documentation
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: grey
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant

repo_url: https://github.com/openvk/docs
repo_name: openvk/docs

nav:
  - 'Main page': 'index.md'
  - Chandler:
    - 'chandler/about.md'
    - 'chandler/installing.md'
  - 'OpenVK Engine':
    - 'openvk_engine/about.md'
    - 'API':
      - 'Objects':
        - 'Audio Genres': 'openvk_engine/api/objects/audio_genres.md'
        - 'Audio': 'openvk_engine/api/objects/audio.md'
        - 'Playlist': 'openvk_engine/api/objects/playlist.md'
        - 'User': 'openvk_engine/api/objects/user.md'
        - 'Group': 'openvk_engine/api/objects/group.md'
      - 'Methods':
        - 'Account':
          - 'Account.getProfileInfo': 'openvk_engine/api/methods/account/getProfileInfo.md'
          - 'Account.getInfo': 'openvk_engine/api/methods/account/getInfo.md'
          - 'Account.setOnline': 'openvk_engine/api/methods/account/setOnline.md'
          - 'Account.getCounters': 'openvk_engine/api/methods/account/getCounters.md'
          - 'Account.saveProfileInfo': 'openvk_engine/api/methods/account/saveProfileInfo.md'
          - 'Account.getBalance': 'openvk_engine/api/methods/account/getBalance.md'
          - 'Account.getOvkSettings': 'openvk_engine/api/methods/account/getOvkSettings.md'
          - 'Account.sendVotes': 'openvk_engine/api/methods/account/sendVotes.md'
          - 'Account.ban': 'openvk_engine/api/methods/account/ban.md'
          - 'Account.unban': 'openvk_engine/api/methods/account/unban.md'
        - 'Audio':
          - 'Audio.getById': 'openvk_engine/api/methods/audio/getById.md'
          - 'Audio.isLagtrain': 'openvk_engine/api/methods/audio/isLagtrain.md'
          - 'Audio.getPopular': 'openvk_engine/api/methods/audio/getPopular.md'
          - 'Audio.search': 'openvk_engine/api/methods/audio/search.md'
          - 'Audio.getCount': 'openvk_engine/api/methods/audio/getCount.md'
          - 'Audio.get': 'openvk_engine/api/methods/audio/get.md'
          - 'Audio.getLyrics': 'openvk_engine/api/methods/audio/getLyrics.md'
          - 'Audio.beacon': 'openvk_engine/api/methods/audio/beacon.md'
          - 'Audio.setBroadcast': 'openvk_engine/api/methods/audio/setBroadcast.md'
          - 'Audio.getBroadcastList': 'openvk_engine/api/methods/audio/getBroadcastList.md'
          - 'Audio.edit': 'openvk_engine/api/methods/audio/edit.md'
          - 'Audio.add': 'openvk_engine/api/methods/audio/add.md'
          - 'Audio.delete': 'openvk_engine/api/methods/audio/delete.md'
          - 'Audio.getAlbums': 'openvk_engine/api/methods/audio/getAlbums.md'
          - 'Audio.searchAlbums': 'openvk_engine/api/methods/audio/searchAlbums.md'
          - 'Audio.addAlbum': 'openvk_engine/api/methods/audio/addAlbum.md'
          - 'Audio.editAlbum': 'openvk_engine/api/methods/audio/editAlbum.md'
          - 'Audio.deleteAlbum': 'openvk_engine/api/methods/audio/deleteAlbum.md'
          - 'Audio.moveToAlbum': 'openvk_engine/api/methods/audio/moveToAlbum.md'
          - 'Audio.removeFromAlbum': 'openvk_engine/api/methods/audio/removeFromAlbum.md'
          - 'Audio.bookmarkAlbum': 'openvk_engine/api/methods/audio/bookmarkAlbum.md'
          - 'Audio.unbookmarkAlbum': 'openvk_engine/api/methods/audio/unbookmarkAlbum.md'
        - 'Board':
          - 'Board.addTopic': 'openvk_engine/api/methods/board/addTopic.md'
          - 'Board.closeTopic': 'openvk_engine/api/methods/board/closeTopic.md'
          - 'Board.createComment': 'openvk_engine/api/methods/board/createComment.md'
          - 'Board.deleteComment': 'openvk_engine/api/methods/board/deleteComment.md'
          - 'Board.deleteTopic': 'openvk_engine/api/methods/board/deleteTopic.md'
          - 'Board.editTopic': 'openvk_engine/api/methods/board/editTopic.md'
          - 'Board.fixTopic': 'openvk_engine/api/methods/board/fixTopic.md'
          - 'Board.getComments': 'openvk_engine/api/methods/board/getComments.md'
          - 'Board.getTopics': 'openvk_engine/api/methods/board/getTopics.md'
          - 'Board.openTopic': 'openvk_engine/api/methods/board/openTopic.md'
          - 'Board.unfixTopic': 'openvk_engine/api/methods/board/unfixTopic.md'
        - 'Friends':
          - 'Friends.add': 'openvk_engine/api/methods/friends/add.md'
          - 'Friends.areFriends': 'openvk_engine/api/methods/friends/areFriends.md'
          - 'Friends.delete': 'openvk_engine/api/methods/friends/delete.md'
          - 'Friends.get': 'openvk_engine/api/methods/friends/get.md'
          - 'Friends.getRequests': 'openvk_engine/api/methods/friends/getRequests.md'
        - 'Gifts':
          - 'Gifts.get': 'openvk_engine/api/methods/gifts/get.md'
          - 'Gifts.getCategories': 'openvk_engine/api/methods/gifts/getCategories.md'
          - 'Gifts.getGiftsInCategory': 'openvk_engine/api/methods/gifts/getGiftsInCategory.md'
          - 'Gifts.send': 'openvk_engine/api/methods/gifts/send.md'
        - 'Groups':
          - 'Groups.create': 'openvk_engine/api/methods/groups/create.md'
          - 'Groups.edit': 'openvk_engine/api/methods/groups/edit.md'
          - 'Groups.get': 'openvk_engine/api/methods/groups/get.md'
          - 'Groups.getById': 'openvk_engine/api/methods/groups/getById.md'
          - 'Groups.getMembers': 'openvk_engine/api/methods/groups/getMembers.md'
          - 'Groups.getSettings': 'openvk_engine/api/methods/groups/getSettings.md'
          - 'Groups.isMember': 'openvk_engine/api/methods/groups/isMember.md'
          - 'Groups.join': 'openvk_engine/api/methods/groups/join.md'
          - 'Groups.leave': 'openvk_engine/api/methods/groups/leave.md'
          - 'Groups.search': 'openvk_engine/api/methods/groups/search.md'
        - 'Likes':
          - 'Likes.add': 'openvk_engine/api/methods/likes/add.md'
          - 'Likes.delete': 'openvk_engine/api/methods/likes/delete.md'
          - 'Likes.getList': 'openvk_engine/api/methods/likes/getList.md'
          - 'Likes.isLiked': 'openvk_engine/api/methods/likes/isLiked.md'
        - 'Messages':
          - 'Messages.delete': 'openvk_engine/api/methods/messages/delete.md'
          - 'Messages.edit': 'openvk_engine/api/methods/messages/edit.md'
          - 'Messages.getById': 'openvk_engine/api/methods/messages/getById.md'
          - 'Messages.getConversations': 'openvk_engine/api/methods/messages/getConversations.md'
          - 'Messages.getConversationsById': 'openvk_engine/api/methods/messages/getConversationsById.md'
          - 'Messages.getHistory': 'openvk_engine/api/methods/messages/getHistory.md'
          - 'Messages.getLongPollHistory': 'openvk_engine/api/methods/messages/getLongPollHistory.md'
          - 'Messages.getLongPollServer': 'openvk_engine/api/methods/messages/getLongPollServer.md'
          - 'Messages.restore': 'openvk_engine/api/methods/messages/restore.md'
          - 'Messages.send': 'openvk_engine/api/methods/messages/send.md'
        - 'Newsfeed':
          - 'Newsfeed.addBan': 'openvk_engine/api/methods/newsfeed/addBan.md'
          - 'Newsfeed.deleteBan': 'openvk_engine/api/methods/newsfeed/deleteBan.md'
          - 'Newsfeed.get': 'openvk_engine/api/methods/newsfeed/get.md'
          - 'Newsfeed.getBanned': 'openvk_engine/api/methods/newsfeed/getBanned.md'
          - 'Newsfeed.getGlobal': 'openvk_engine/api/methods/newsfeed/getGlobal.md'
        - 'Notes':
          - 'Notes.add': 'openvk_engine/api/methods/notes/add.md'
          - 'Notes.createComment': 'openvk_engine/api/methods/notes/createComment.md'
          - 'Notes.delete': 'openvk_engine/api/methods/notes/delete.md'
          - 'Notes.edit': 'openvk_engine/api/methods/notes/edit.md'
          - 'Notes.get': 'openvk_engine/api/methods/notes/get.md'
          - 'Notes.getById': 'openvk_engine/api/methods/notes/getById.md'
          - 'Notes.getComments': 'openvk_engine/api/methods/notes/getComments.md'
        - 'Notifications':
          - 'Notifications.get': 'openvk_engine/api/methods/notifications/get.md'
          - 'Notifications.markAsViewed': 'openvk_engine/api/methods/notifications/markAsViewed.md'
        - 'Ovk':
          - 'Ovk.aboutInstance': 'openvk_engine/api/methods/ovk/aboutInstance.md'
          - 'Ovk.chickenWings': 'openvk_engine/api/methods/ovk/chickenWings.md'
          - 'Ovk.test': 'openvk_engine/api/methods/ovk/test.md'
          - 'Ovk.version': 'openvk_engine/api/methods/ovk/version.md'
        - 'Pay':
          - 'Pay.getIdByMarketingId': 'openvk_engine/api/methods/pay/getIdByMarketingId.md'
          - 'Pay.verifyOrder': 'openvk_engine/api/methods/pay/verifyOrder.md'
        - 'Photos':
          - 'Photos.createAlbum': 'openvk_engine/api/methods/photos/createAlbum.md'
          - 'Photos.delete': 'openvk_engine/api/methods/photos/delete.md'
          - 'Photos.deleteAlbum': 'openvk_engine/api/methods/photos/deleteAlbum.md'
          - 'Photos.edit': 'openvk_engine/api/methods/photos/edit.md'
          - 'Photos.editAlbum': 'openvk_engine/api/methods/photos/editAlbum.md'
          - 'Photos.get': 'openvk_engine/api/methods/photos/get.md'
          - 'Photos.getAlbums': 'openvk_engine/api/methods/photos/getAlbums.md'
          - 'Photos.getAlbumsCount': 'openvk_engine/api/methods/photos/getAlbumsCount.md'
          - 'Photos.getAll': 'openvk_engine/api/methods/photos/getAll.md'
          - 'Photos.getById': 'openvk_engine/api/methods/photos/getById.md'
          - 'Photos.getComments': 'openvk_engine/api/methods/photos/getComments.md'
          - 'Photos.getOwnerPhotoUploadServer': 'openvk_engine/api/methods/photos/getOwnerPhotoUploadServer.md'
          - 'Photos.getWallUploadServer': 'openvk_engine/api/methods/photos/getWallUploadServer.md'
          - 'Photos.save': 'openvk_engine/api/methods/photos/save.md'
          - 'Photos.saveOwnerPhoto': 'openvk_engine/api/methods/photos/saveOwnerPhoto.md'
          - 'Photos.saveWallPhoto': 'openvk_engine/api/methods/photos/saveWallPhoto.md'
        - 'Polls':
          - 'Polls.addVote': 'openvk_engine/api/methods/polls/addVote.md'
          - 'Polls.create': 'openvk_engine/api/methods/polls/create.md'
          - 'Polls.deleteVote': 'openvk_engine/api/methods/polls/deleteVote.md'
          - 'Polls.getById': 'openvk_engine/api/methods/polls/getById.md'
          - 'Polls.getVoters': 'openvk_engine/api/methods/polls/getVoters.md'
        - 'Reports':
          - 'Reports.add': 'openvk_engine/api/methods/reports/add.md'
        - 'Status':
          - 'Status.get': 'openvk_engine/api/methods/status/get.md'
          - 'Status.get': 'openvk_engine/api/methods/status/set.md'
        - 'Users':
          - 'Users.get': 'openvk_engine/api/methods/users/get.md'
          - 'Users.getFollowers': 'openvk_engine/api/methods/users/getFollowers.md'
          - 'Users.search': 'openvk_engine/api/methods/users/search.md'
        - 'Utils':
          - 'Utils.getServerTime': 'openvk_engine/api/methods/utils/getServerTime.md'
          - 'Utils.resolveScreenName': 'openvk_engine/api/methods/utils/resolveScreenName.md'
        - 'Video':
          - 'Video.get': 'openvk_engine/api/methods/video/get.md'
          - 'Video.search': 'openvk_engine/api/methods/video/search.md'
        - 'Wall':
          - 'Wall.checkCopyrightLink': 'openvk_engine/api/methods/wall/checkCopyrightLink.md'
          - 'Wall.createComment': 'openvk_engine/api/methods/wall/createComment.md'
          - 'Wall.delete': 'openvk_engine/api/methods/wall/delete.md'
          - 'Wall.deleteComment': 'openvk_engine/api/methods/wall/deleteComment.md'
          - 'Wall.edit': 'openvk_engine/api/methods/wall/edit.md'
          - 'Wall.editComment': 'openvk_engine/api/methods/wall/editComment.md'
          - 'Wall.get': 'openvk_engine/api/methods/wall/get.md'
          - 'Wall.getById': 'openvk_engine/api/methods/wall/getById.md'
          - 'Wall.getComment': 'openvk_engine/api/methods/wall/getComment.md'
          - 'Wall.getComments': 'openvk_engine/api/methods/wall/getComments.md'
          - 'Wall.pin': 'openvk_engine/api/methods/wall/pin.md'
          - 'Wall.post': 'openvk_engine/api/methods/wall/post.md'
          - 'Wall.repost': 'openvk_engine/api/methods/wall/repost.md'
          - 'Wall.unpin': 'openvk_engine/api/methods/wall/unpin.md'
    - 'openvk_engine/api/overview.md'
    - 'openvk_engine/themepack_creation.md'
  - 'Tutorials':
    - 'openvk_engine/centos8_installation.md'
    - 'openvk_engine/ton_integration.md'

copyright: Copyright &copy; 2021-2025 OpenVK Team and contributors

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/openvk/openvk
      name: OpenVK on GitHub
    - icon: fontawesome/brands/telegram
      link: https://t.me/openvk
      name: OpenVK on Telegram
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@openvk
      name: OpenVK on Mastodon
    - icon: fontawesome/solid/paper-plane
      link: mailto:openvk@tutanota.com
      name: Mail OpenVK

plugins:
  - git-revision-date

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
